### PR TITLE
docs(readme): updated install and require in readme

### PR DESCRIPTION
**Pull request by turbobeast**
added @bubltechnology prefix to install and require examples in readme -- npm version badge

### CODE REVIEW

**Comment by turbobeast** [comment]
we'll see if this publishes

**Comment by jeffheifetz** [comment]
OK, but then I'm gonna make you pull the analyzer into its own package

**Comment by turbobeast** [comment]
Okay, but how are we going to release the analyzer?

**Comment by jeffheifetz** [comment]
Hah, thats so meta ...

**Pull request merged**
